FROM anapsix/alpine-java
LABEL maintainer="rahulwankhade92@gmail.com"
COPY /target/MyFirstSBApp-0.0.1-SNAPSHOT.jar /home/MyFirstSBApp-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","/home/MyFirstSBApp-0.0.1-SNAPSHOT.jar"]