FROM anapsix/alpine-java
LABEL maintainer="rahulwankhade92@gmail.com"
COPY /target/spring-boot-web-jsp-1.0.war /home/spring-boot-web-jsp-1.0.war
CMD ["java","-jar","/home/spring-boot-web-jsp-1.0.war"]